import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    shop: 'Shop',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    orders: 'My Orders',
    admin: 'Admin',
    cart: 'Cart',
    viewStorefront: 'View storefront',
    adminStudio: 'Admin Studio',
    language: 'العربية',
    loading: 'Loading',
    browse: 'Browse',
    save: 'Save',
    saving: 'Saving...',
    remove: 'Remove',
    edit: 'Edit',
    delete: 'Delete',
    active: 'Active',
    hidden: 'Hidden',
    featured: 'Featured',
    normal: 'Normal',
    preview: 'Preview',
    search: 'Search',
    emailAction: 'Email',
    cancelEdit: 'Cancel edit',
    cancel: 'Cancel',
    confirmAction: 'Confirm',

    // Toasts / system feedback
    welcomeBack: 'Welcome back',
    accountReady: 'Your account is ready',
    loggedOut: 'Logged out',
    addedToCart: 'Added to cart',
    removedFromCart: 'Removed from cart',
    productOutOfStock: 'This product is out of stock',
    onlyAvailable: 'Only {count} available',
    discountEnterCode: 'Enter a discount code',
    discountApplied: 'Discount code applied',
    discountRemoved: 'Discount removed',
    invalidDiscountCode: 'Invalid discount code',
    couldNotPlaceOrder: 'Could not place order',
    cashUnavailable: 'Cash on delivery is currently unavailable',
    instapayUnavailable: 'Instapay is currently unavailable',
    noPaymentMethodAvailable: 'No payment method is currently available',
    settingsSaved: 'Settings saved',
    imageUploaded: 'Image uploaded',
    imageUploadFailed: 'Image upload failed',
    qrUploaded: 'Instapay QR uploaded',
    qrUploadFailed: 'QR upload failed',
    productSaved: 'Product saved',
    productDeleted: 'Product deleted',
    categorySaved: 'Category saved',
    categoryDeleted: 'Category deleted',
    offerSaved: 'Offer saved',
    offerDeleted: 'Offer deleted',
    offerEmailSent: 'Offer email sent to customers',
    discountSaved: 'Discount code saved',
    discountDeleted: 'Discount code deleted',
    discountEmailSent: 'Discount email sent to customers',
    paymentStatusUpdated: 'Payment status updated',

    // Validation
    fullNameRequired: 'Full name is required',
    validEmailRequired: 'Valid email is required',
    phoneRequired: 'Phone is required',
    addressRequired: 'Address is required',
    cityRequired: 'City or area is required',
    passwordMin: 'Password must be at least 6 characters',
    choosePaymentTiming: 'Choose when you will pay',
    checkingAccount: 'Checking your account',
    checkingAdminAccess: 'Checking admin access',

    homeEyebrow: 'Signature table linen',
    homeTitle: 'Printed linen for tables with a quiet kind of luxury.',
    homeCopy: 'Premium table linen with warm prints, natural colors, and a boutique finish made for hosting, gifting, and soft everyday rituals.',
    shopCollection: 'Shop collection',
    readStory: 'Read the story',
    homePillPrinted: 'Printed linen',
    homePillSmall: 'Boutique finish',
    homePillPricing: 'Elegant hosting',
    newSeasonPieces: 'Curated pieces',
    featuredPieces: 'Featured pieces',
    featuredTitle: 'Made for the table everyone remembers',
    viewAll: 'View all',
    categories: 'Categories',
    categoriesTitle: 'Shop by mood and craft',
    category: 'Category',
    categoryCopy: 'Explore refined textures, expressive prints, and graceful table styling essentials.',
    brandStory: 'Brand story',
    brandStoryTitle: 'Warm details, premium finish, effortless hosting.',
    brandStoryCopy: 'Every collection starts with a mood: garden afternoons, softened light, and tables that feel personal. ByJojo keeps the experience polished without losing the warmth of home hospitality.',
    naturalPalette: 'Natural palette',
    naturalPaletteCopy: 'Ivory, sand, sage, olive, and muted gold.',
    tableReady: 'Table-ready pieces',
    tableReadyCopy: 'Designed to make setup feel finished with less effort.',
    readySetup: 'Ready for your next table setup?',
    chooseSignature: 'Choose your signature linen piece.',
    shopNow: 'Shop now',

    shopEyebrow: 'Shop ByJojo',
    shopTitle: 'Premium linen collection',
    shopCopy: 'Browse printed linen and future embroidery pieces by category, price, and newest arrivals.',
    refine: 'Refine',
    allCategories: 'All categories',
    newest: 'Newest first',
    priceLow: 'Price: low to high',
    priceHigh: 'Price: high to low',
    productsLoadError: 'Could not load products',
    backendHint: 'Please make sure the backend is running.',
    noProductsFound: 'No products found',
    tryAnotherFilter: 'Try another category or sort option.',

    addToCart: 'Add to cart',
    previousImage: 'Previous product image',
    nextImage: 'Next product image',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
    material: 'Material',
    premiumLinen: 'Premium linen',
    use: 'Use',
    tableSetup: 'Table setup',
    stock: 'Stock',
    available: 'Available',
    outOfStock: 'Out of stock',
    productNotFound: 'Product not found',
    onlyLeft: 'Only {count} left',
    availableToOrder: 'Available to order',
    currentlyOutOfStock: 'Currently out of stock',
    updateCartToContinue: 'Update cart to continue',
    cartStockWarning: 'Some cart quantities are higher than the available stock. Please adjust them before checkout.',
    quantityReducedStock: 'Quantity reduced to available stock before checkout.',
    unavailableRemoveToContinue: 'This product is currently unavailable. Remove it to continue checkout.',
    sellOutSoon: 'This piece may sell out soon.',
    contactForUnavailable: 'This product is currently unavailable. Please check back soon or contact ByJojo.',

    yourCart: 'Your cart',
    emptyCart: 'Your cart is empty',
    emptyCartCopy: 'Add a linen piece from the shop to begin checkout.',
    summary: 'Summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    total: 'Total',
    checkout: 'Checkout',
    removeItem: 'Remove item',

    checkoutTitle: 'Checkout',
    secureCheckout: 'Secure checkout',
    checkoutCopy: 'Share your delivery details and choose the payment method that works best for you.',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    city: 'City / area',
    address: 'Address',
    notes: 'Notes',
    paymentMethod: 'Payment method',
    cashOnDelivery: 'Cash on delivery',
    instapay: 'Instapay',
    cashPaymentCopy: 'Pay when your ByJojo order arrives.',
    instapayPaymentCopy: 'Transfer by Instapay and share the proof for confirmation.',
    instapayDetails: 'Instapay details',
    instapayInstructions: 'Use the number or QR code, then tell us how you will confirm the transfer.',
    instapayNumber: 'Instapay number',
    paidNow: 'I paid / will send proof now',
    payAfterConfirmation: 'I will pay on delivery',
    paymentReference: 'Payment reference',
    paymentReferencePlaceholder: 'Sender name or transfer reference',
    proofSentVia: 'Proof sent via',
    other: 'Other',
    paymentNote: 'Payment note',
    paymentNotePlaceholder: 'Any extra payment details',
    instapayProofCopy: 'After placing the order, send the Instapay transfer screenshot on WhatsApp or Instagram so ByJojo can verify it quickly.',
    sendProofDirectly: 'Send proof directly',
    openInstagramDm: 'Open Instagram DM',
    openWhatsAppChat: 'Open WhatsApp chat',
    proofButtonsCopy: 'Choose a channel, then open the chat to send your transfer screenshot.',
    checkoutTrustCopy: 'Your order details go directly to ByJojo. The team will contact you to confirm delivery and payment.',
    addFromAdmin: 'Add it from admin settings',
    placeOrder: 'Place order',
    placingOrder: 'Placing order...',
    orderPlaced: 'Order placed successfully',
    orderSummary: 'Order summary',
    addProductsBeforeCheckout: 'Add products before checkout.',
    discountCodeHelp: 'Enter a code if the customer received one from ByJojo.',
    appliedCode: 'Applied code',

    orderSuccessEyebrow: 'Order received',
    orderSuccessTitle: 'Thank you. Your ByJojo order is now in progress.',
    orderSuccessCopy: 'We saved your order and sent the details to the ByJojo team. You will be contacted soon to confirm delivery and payment.',
    orderSuccessMissing: 'Order details unavailable',
    orderSuccessMissingCopy: 'We could not load this confirmation page. You can still check your account orders.',
    continueShopping: 'Continue shopping',
    viewMyOrders: 'View my orders',
    instapayNextStep: 'Instapay next step',
    instapaySuccessCopy: 'If you selected Instapay, please make sure the payment proof is sent through the channel you selected during checkout.',
    orderItems: 'Order items',
    piecesInOrder: '{count} pieces in this order',
    byjojoContactSoon: 'ByJojo will contact you soon to confirm the payment and delivery details.',

    account: 'Account',
    myOrdersTitle: 'My orders',
    myOrdersCopy: 'Track your ByJojo orders and see the pieces saved with each checkout.',
    totalOrders: 'Total orders',
    noOrdersYet: 'No orders yet',
    noOrdersCopy: 'Your ByJojo orders will appear here after checkout.',
    couldNotLoadOrders: 'Could not load orders',
    order: 'Order',
    qty: 'Qty',

    aboutEyebrow: 'About ByJojo',
    aboutTitle: 'A softer way to dress the table.',
    aboutCopy: 'ByJojo is a premium home and table linen brand built around elegant prints, natural colors, and simple pieces that make hosting feel thoughtful without becoming fussy.',
    contactEyebrow: 'Contact',
    contactTitle: 'We would love to help.',
    contactOrdersTitle: 'Orders',
    contactOrdersCopy: 'For sizing, delivery, and product questions, reach out through WhatsApp or Instagram.',
    collaborations: 'Collaborations',
    collaborationsCopy: 'For home styling, gifting, or boutique collaborations, send us your request by email.',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    emailByJojo: 'Email ByJojo',
    notFoundTitle: 'Page not found',
    notFoundCopy: 'This page is not available. Let’s take you back to the collection.',
    goToShop: 'Go to shop',

    loginTitle: 'Login',
    password: 'Password',
    loggingIn: 'Logging in...',
    newToByJojo: 'New to ByJojo?',
    createAccount: 'Create account',
    signupTitle: 'Create account',
    creating: 'Creating...',
    signup: 'Sign up',
    alreadyAccount: 'Already have an account?',
    adminLoginTitle: 'Admin login',
    adminLoginCopy: 'Use the admin account created by the seed script.',

    footerEyebrow: 'Premium table linen',
    footerCopy: 'Warm printed linen and table setup pieces for thoughtful hosting, gifting, and beautiful everyday rituals.',
    visitCollection: 'Visit the collection',
    shopLatest: 'Shop latest pieces',
    explore: 'Explore',
    footerRights: 'All rights reserved.',
    footerLine: 'Made for warm homes and beautiful tables.',
    tableLinen: 'Table Linen',
    toggleMenu: 'Toggle menu',
    viewProduct: 'View product',
    curatedWarmerTable: 'Curated pieces for a warmer table.',
    premiumTableLinen: 'Premium table linen',
    quality: 'Quality',
    contactOptions: 'Contact options',
    byjojoSupport: 'ByJojo support',
    contactClosingTitle: 'Send the details, and ByJojo will help.',
    contactClosingCopy: 'For the fastest reply, include the product name, your area, and your preferred payment method.',
    emailNotAdded: 'Email not added',
    noPaymentMethodsCustomer: 'No payment methods are currently available. Please contact ByJojo before placing an order.',
    instapayQrAlt: 'Instapay QR',
    relatedProductsEyebrow: 'You may also like',
    relatedProductsTitle: 'Pieces that complete the same mood',
    productSeoFallback: 'Premium ByJojo table linen piece for elegant table styling.',
    printedLinen: 'Printed Linen',
    embroidery: 'Embroidery',
    code: 'Code',
    discountType: 'Discount type',
    discountValue: 'Discount value',
    expiryDate: 'Expiry date',
    ownerNote: 'Owner note',
    codePreview: 'Code preview',
    offerPreview: 'Offer preview',
    useAtCheckout: 'Use at checkout',
    minimum: 'Minimum',
    expires: 'Expires',
    status: 'Status',
    unlimited: 'Unlimited',
    noExpiry: 'No expiry',
    existingCodes: 'Existing codes',
    searchDiscountCodes: 'Search discount codes...',
    discountCodesFoundEmpty: 'No discount codes found',
    discountCodesFoundEmptyCopy: 'Create a code for campaigns, loyal customers, or limited-time checkout incentives.',
    discountCodeCreated: 'Discount code created',
    discountCodeUpdated: 'Discount code updated',
    couldNotSaveDiscountCode: 'Could not save discount code',
    couldNotDeleteDiscountCode: 'Could not delete discount code',
    couldNotEmailDiscountCode: 'Could not email discount code',
    codeCopied: 'Code copied',
    couldNotCopyCode: 'Could not copy code',
    confirmDeleteDiscountCode: 'Delete discount code "{code}"?',
    confirmEmailDiscountCode: 'Email "{code}" to all registered customers?',
    confirmDeleteProduct: 'Delete "{name}"?',
    confirmDeleteCategory: 'Delete "{name}"?',
    confirmDeleteOffer: 'Delete offer "{title}"?',
    confirmEmailOffer: 'Email "{title}" to all registered customers?',
    confirmDeleteMessage: 'This action cannot be undone.',
    confirmEmailMessage: 'Registered customers will receive this email.',
    discountCodesNoteFull: 'Create polished discount codes with minimum order amounts, expiry dates, usage limits, and customer email campaigns. Codes are validated again by the backend during checkout.',
    discountCodeFormHelp: 'Set the code, discount value, eligibility rules, and whether customers can use it at checkout.',
    discountOwnerNoteCopy: 'Percentage codes are best for campaigns like "10% off." Fixed codes are best for clean values like "500 EGP off." The backend recalculates the discount when the order is placed, so customers cannot fake the total from the browser.',
    existingCodesCopy: 'Manage campaign codes, copy them quickly, or email them to registered customers.',
    usageProgress: 'Usage progress',
    usesRemaining: '{count} uses remaining',
    noUsageLimit: 'This code has no usage limit.',
    noCategory: 'No category',
    customer: 'Customer',
    openOrders: 'Open orders',
    manageProducts: 'Manage products',
    orderActivity: 'Order activity',
    recentOrders: 'Recent orders',
    inventory: 'Inventory',
    lowStock: 'Low stock',
    performance: 'Performance',
    bestSellingPieces: 'Best-selling pieces',
    noLowStockProducts: 'No low-stock products right now.',
    bestSellingEmpty: 'Best-selling products will appear after orders are placed.',
    left: 'left',
    sold: 'sold',
    averageOrder: 'avg. order',
    today: 'today',
    pending: 'pending',
    awaitingPayment: 'Awaiting payment',
    awaitingPaymentNote: 'Instapay orders needing confirmation',
    registeredCustomerAccounts: 'Registered customer accounts',
    activeHidden: '{active} active · {hidden} hidden',
    lowStockNote: 'Products with 3 pieces or fewer',
    dashboardNoteFull: 'A quick business snapshot for ByJojo: sales, orders, payment follow-ups, low stock pieces, and recent customer activity.',
    lowStockCopy: 'Keep these products updated before they sell out.',
    customerCommunity: 'Customer community',
    customersNoteFull: 'Registered customers appear here with their order count, total spend, last order date, and quick contact shortcuts.',
    searchCustomers: 'Search name, email, or phone...',
    registeredCustomers: 'Registered customers',
    customerOrders: 'Customer orders',
    customerRevenue: 'Customer revenue',
    totalSpent: 'Total spent',
    lastOrder: 'Last order',
    noCustomersFound: 'No customers found',
    noCustomersFoundCopy: 'Try another search term or wait for customers to create accounts.',
    orderStatusPending: 'Pending',
    orderStatusConfirmed: 'Confirmed',
    orderStatusPreparing: 'Preparing',
    orderStatusOutForDelivery: 'Out for delivery',
    orderStatusDelivered: 'Delivered',
    orderStatusCancelled: 'Cancelled',
    paymentStatusPending: 'Pending',
    paymentStatusAwaitingConfirmation: 'Awaiting confirmation',
    paymentStatusPaid: 'Paid',
    couldNotUpdateOrder: 'Could not update order',
    couldNotUpdatePaymentStatus: 'Could not update payment status',
    timing: 'Timing',

    adminOwnerTools: 'Owner tools',
    adminProductsTitle: 'Products',
    adminProductsNote: 'Add or edit products here. You can update prices, descriptions, categories, and images anytime. For best quality, use clear square or vertical images with soft natural light.',
    adminAddProduct: 'Add new product',
    adminEditProduct: 'Edit product',
    adminProductImageNote: 'Choose product images from your computer. They upload to Cloudinary automatically.',
    productName: 'Product name',
    productNameAr: 'Product name Arabic',
    priceEgp: 'Price EGP',
    selectCategory: 'Select category',
    description: 'Description',
    descriptionAr: 'Arabic description',
    featuredOnHome: 'Featured on home',
    visibleInShop: 'Visible in shop',
    productImages: 'Product images',
    mainImageNote: 'First/main image appears on cards.',
    chooseImage: 'Choose image',
    replaceImage: 'Replace image',
    uploading: 'Uploading...',
    mainImage: 'Main image',
    setMain: 'Set main',
    imagesReady: 'images ready',
    updateProduct: 'Update product',
    addProduct: 'Add product',
    searchProducts: 'Search products by name or category...',

    adminCategoriesTitle: 'Categories',
    adminCategoriesNote: 'Create and manage product categories. You can hide a category without deleting it, and you can decide whether it appears on the customer home page.',
    storeStructure: 'Store structure',
    addCategory: 'Add category',
    updateCategory: 'Update category',
    addNewCategory: 'Add new category',
    editCategory: 'Edit category',
    categoryName: 'Category name',
    categoryImage: 'Category image',
    showOnHome: 'Show on home',
    activeInShop: 'Active in shop',

    settingsTitle: 'Settings',
    settingsEyebrow: 'Checkout controls',
    settingsNote: 'Delivery fee, Instapay number, and QR code are shown during checkout. Any changes here update the customer website automatically.',
    storeSettings: 'Store settings',
    storeSettingsCopy: 'Keep contact, payment, and announcement details updated for customers.',
    storeName: 'Store name',
    deliveryFee: 'Delivery fee',
    whatsappNumber: 'WhatsApp number',
    instagramUrl: 'Instagram URL',
    contactEmail: 'Contact email',
    announcementText: 'Announcement text',
    instapayQr: 'Instapay QR',
    instapayQrCopy: 'Customers see this image when they select Instapay during checkout.',
    saveSettings: 'Save settings',
    replaceQr: 'Replace QR image',
    chooseQr: 'Choose QR image',
    paymentMethods: 'Payment methods',
    checkoutAvailability: 'Checkout availability',
    paymentSettingsCopy: 'Turn payment methods on or off. Customers will only see the enabled options during checkout.',
    cashToggleCopy: 'Customers can pay when the order arrives.',
    instapayToggleCopy: 'Customers can transfer by Instapay and send proof.',
    paymentMethodWarning: 'At least one payment method should be enabled before launch.',
    instapayDisabledNote: 'Instapay is currently disabled. The QR and number are saved, but customers will not see Instapay at checkout.',

    overviewTitle: 'Overview / Analytics',
    overviewNote: 'Use this dashboard to quickly review store activity, sales totals, product count, customers, and recent orders.',
    products: 'Products',
    customers: 'Customers',
    revenue: 'Revenue',
    adminOrdersTitle: 'Orders',
    adminOrdersNote: 'Review new orders here, then update the order status as each package moves from confirmation to delivery.',
    orderUpdated: 'Order updated',
    orderStatus: 'Order status',
    paymentStatus: 'Payment status',
    orderDetails: 'Order details',
    noOrdersAdmin: 'No orders yet',
    noOrdersAdminCopy: 'New customer orders will appear here.',
    reviewOrdersCopy: 'Review customer orders, confirm Instapay payments, and move each order through preparation and delivery.',

    offersTitle: 'Offers',
    offersNote: 'Offers can be applied to selected products only. Customers will see the offer price automatically in the shop and product page.',
    offerTitle: 'Offer title',
    percentage: 'Percentage',
    fixed: 'Fixed',
    salePrice: 'Sale price',
    updateOffer: 'Update offer',
    createOffer: 'Create offer',
    chooseProducts: 'Choose products',
    selectedPieces: 'Selected pieces',
    existingOffers: 'Existing offers',
    noOffersYet: 'No offers yet',

    discountCodesTitle: 'Discount Codes',
    discountCodesNote: 'Create customer discount codes with minimum order amounts and usage limits. You can email codes to registered customers from here.',
    minimumOrder: 'Minimum order',
    usageLimit: 'Usage limit',
    updateCode: 'Update code',
    createCode: 'Create code',
    used: 'used',
  },

  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    about: 'من نحن',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    orders: 'طلباتي',
    admin: 'لوحة التحكم',
    cart: 'السلة',
    viewStorefront: 'عرض الموقع',
    adminStudio: 'استوديو الإدارة',
    language: 'English',
    loading: 'جار التحميل',
    browse: 'تصفح',
    save: 'حفظ',
    saving: 'جار الحفظ...',
    remove: 'حذف',
    edit: 'تعديل',
    delete: 'حذف',
    active: 'نشط',
    hidden: 'مخفي',
    featured: 'مميز',
    normal: 'عادي',
    preview: 'معاينة',
    search: 'بحث',
    emailAction: 'إرسال بريد',
    cancelEdit: 'إلغاء التعديل',
    cancel: 'إلغاء',
    confirmAction: 'تأكيد',

    // Toasts / system feedback
    welcomeBack: 'مرحبًا بعودتك',
    accountReady: 'تم إنشاء حسابك',
    loggedOut: 'تم تسجيل الخروج',
    addedToCart: 'تمت الإضافة للسلة',
    removedFromCart: 'تم حذف المنتج من السلة',
    productOutOfStock: 'هذا المنتج غير متاح حالياً',
    onlyAvailable: 'متاح فقط {count}',
    discountEnterCode: 'اكتبي كود الخصم',
    discountApplied: 'تم تطبيق كود الخصم',
    discountRemoved: 'تم حذف الخصم',
    invalidDiscountCode: 'كود الخصم غير صحيح',
    couldNotPlaceOrder: 'تعذر تسجيل الطلب',
    cashUnavailable: 'الدفع عند الاستلام غير متاح حالياً',
    instapayUnavailable: 'إنستاباي غير متاح حالياً',
    noPaymentMethodAvailable: 'لا توجد طريقة دفع متاحة حالياً',
    settingsSaved: 'تم حفظ الإعدادات',
    imageUploaded: 'تم رفع الصورة',
    imageUploadFailed: 'فشل رفع الصورة',
    qrUploaded: 'تم رفع QR إنستاباي',
    qrUploadFailed: 'فشل رفع QR',
    productSaved: 'تم حفظ المنتج',
    productDeleted: 'تم حذف المنتج',
    categorySaved: 'تم حفظ القسم',
    categoryDeleted: 'تم حذف القسم',
    offerSaved: 'تم حفظ العرض',
    offerDeleted: 'تم حذف العرض',
    offerEmailSent: 'تم إرسال العرض للعملاء',
    discountSaved: 'تم حفظ كود الخصم',
    discountDeleted: 'تم حذف كود الخصم',
    discountEmailSent: 'تم إرسال كود الخصم للعملاء',
    paymentStatusUpdated: 'تم تحديث حالة الدفع',

    // Validation
    fullNameRequired: 'الاسم بالكامل مطلوب',
    validEmailRequired: 'البريد الإلكتروني غير صحيح',
    phoneRequired: 'رقم الهاتف مطلوب',
    addressRequired: 'العنوان مطلوب',
    cityRequired: 'المدينة أو المنطقة مطلوبة',
    passwordMin: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    choosePaymentTiming: 'اختاري موعد الدفع',
    checkingAccount: 'جار فحص الحساب',
    checkingAdminAccess: 'جار فحص صلاحية الإدارة',

    homeEyebrow: 'مفروشات طاولة مميزة',
    homeTitle: 'مفروشات طاولة مطبوعة بفخامة هادئة.',
    homeCopy: 'مفروشات طاولة فاخرة بنقوش دافئة وألوان طبيعية ولمسة بوتيك مناسبة للضيافة والهدايا والتفاصيل اليومية الجميلة.',
    shopCollection: 'تسوقي المجموعة',
    readStory: 'اقرئي القصة',
    homePillPrinted: 'مفروشات مطبوعة',
    homePillSmall: 'تشطيب بوتيك',
    homePillPricing: 'ضيافة أنيقة',
    newSeasonPieces: 'قطع مختارة',
    featuredPieces: 'قطع مميزة',
    featuredTitle: 'مصممة للطاولة التي لا تنسى',
    viewAll: 'عرض الكل',
    categories: 'الأقسام',
    categoriesTitle: 'تسوقي حسب الإحساس والحرفة',
    category: 'القسم',
    categoryCopy: 'اكتشفي خامات راقية ونقوش معبرة وتفاصيل أنيقة لتنسيق الطاولة.',
    brandStory: 'قصة البراند',
    brandStoryTitle: 'تفاصيل دافئة، تشطيب فاخر، وضيافة أسهل.',
    brandStoryCopy: 'كل مجموعة تبدأ بإحساس: ضوء ناعم، طاولة شخصية، ولمسات تجعل البيت أجمل. ByJojo تحافظ على الفخامة بدون أن تفقد دفء البيت.',
    naturalPalette: 'ألوان طبيعية',
    naturalPaletteCopy: 'أوف وايت، رملي، سيج، زيتوني، وذهبي هادئ.',
    tableReady: 'جاهزة للطاولة',
    tableReadyCopy: 'مصممة لتجعل التنسيق يبدو مكتملًا بمجهود أقل.',
    readySetup: 'جاهزة لتنسيق طاولتك القادمة؟',
    chooseSignature: 'اختاري قطعة اللينن المميزة.',
    shopNow: 'تسوقي الآن',

    shopEyebrow: 'متجر ByJojo',
    shopTitle: 'مجموعة اللينن الفاخرة',
    shopCopy: 'تصفحي المفروشات المطبوعة والتطريز حسب القسم والسعر والأحدث.',
    refine: 'تصفية',
    allCategories: 'كل الأقسام',
    newest: 'الأحدث أولًا',
    priceLow: 'السعر: من الأقل للأعلى',
    priceHigh: 'السعر: من الأعلى للأقل',
    productsLoadError: 'تعذر تحميل المنتجات',
    backendHint: 'تأكدي أن السيرفر يعمل.',
    noProductsFound: 'لا توجد منتجات',
    tryAnotherFilter: 'جربي قسمًا أو ترتيبًا آخر.',

    addToCart: 'أضيفي للسلة',
    previousImage: 'الصورة السابقة',
    nextImage: 'الصورة التالية',
    decreaseQuantity: 'تقليل الكمية',
    increaseQuantity: 'زيادة الكمية',
    material: 'الخامة',
    premiumLinen: 'لينن فاخر',
    use: 'الاستخدام',
    tableSetup: 'تنسيق الطاولة',
    stock: 'المخزون',
    available: 'متاح',
    outOfStock: 'غير متاح',
    productNotFound: 'المنتج غير موجود',
    onlyLeft: 'متبقي {count} فقط',
    availableToOrder: 'متاح للطلب',
    currentlyOutOfStock: 'غير متاح حالياً',
    updateCartToContinue: 'عدلي السلة للمتابعة',
    cartStockWarning: 'بعض الكميات في السلة أعلى من المخزون المتاح. عدليها قبل إتمام الطلب.',
    quantityReducedStock: 'تم تقليل الكمية حسب المخزون المتاح قبل إتمام الطلب.',
    unavailableRemoveToContinue: 'هذا المنتج غير متاح حالياً. احذفيه للمتابعة.',
    sellOutSoon: 'هذه القطعة قد تنفد قريباً.',
    contactForUnavailable: 'هذا المنتج غير متاح حالياً. يمكنك الرجوع لاحقاً أو التواصل مع ByJojo.',

    yourCart: 'سلتك',
    emptyCart: 'سلتك فارغة',
    emptyCartCopy: 'أضيفي قطعة لينن من المتجر لبدء الطلب.',
    summary: 'الملخص',
    subtotal: 'المجموع الفرعي',
    delivery: 'التوصيل',
    total: 'الإجمالي',
    checkout: 'إتمام الطلب',
    removeItem: 'حذف المنتج',

    checkoutTitle: 'إتمام الطلب',
    secureCheckout: 'إتمام آمن للطلب',
    checkoutCopy: 'اكتبي بيانات التوصيل واختاري طريقة الدفع المناسبة لك.',
    fullName: 'الاسم بالكامل',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    city: 'المدينة / المنطقة',
    address: 'العنوان',
    notes: 'ملاحظات',
    paymentMethod: 'طريقة الدفع',
    cashOnDelivery: 'الدفع عند الاستلام',
    instapay: 'إنستاباي',
    cashPaymentCopy: 'الدفع نقداً عند وصول طلب ByJojo.',
    instapayPaymentCopy: 'حوّلي عبر إنستاباي وأرسلي إثبات التحويل للتأكيد.',
    instapayDetails: 'تفاصيل إنستاباي',
    instapayInstructions: 'استخدمي الرقم أو صورة QR ثم اخبرينا كيف سيتم تأكيد التحويل.',
    instapayNumber: 'رقم إنستاباي',
    paidNow: 'دفعت / سأرسل الإثبات الآن',
    payAfterConfirmation: 'سأدفع عند الاستلام',
    paymentReference: 'مرجع الدفع',
    paymentReferencePlaceholder: 'اسم المرسل أو رقم التحويل',
    proofSentVia: 'إثبات الدفع عبر',
    other: 'أخرى',
    paymentNote: 'ملاحظة الدفع',
    paymentNotePlaceholder: 'أي تفاصيل إضافية عن الدفع',
    instapayProofCopy: 'بعد تأكيد الطلب، أرسلي صورة تحويل إنستاباي على واتساب أو إنستجرام حتى يتم التأكيد بسرعة.',
    sendProofDirectly: 'إرسال الإثبات مباشرة',
    openInstagramDm: 'فتح رسائل إنستجرام',
    openWhatsAppChat: 'فتح محادثة واتساب',
    proofButtonsCopy: 'اختاري وسيلة التواصل، ثم افتحي المحادثة لإرسال صورة التحويل.',
    checkoutTrustCopy: 'بيانات طلبك تصل مباشرة إلى ByJojo. سيتواصل الفريق معك لتأكيد التوصيل والدفع.',
    addFromAdmin: 'أضيفيه من إعدادات الإدارة',
    placeOrder: 'تأكيد الطلب',
    placingOrder: 'جار تأكيد الطلب...',
    orderPlaced: 'تم تسجيل الطلب بنجاح',
    orderSummary: 'ملخص الطلب',
    addProductsBeforeCheckout: 'أضيفي منتجات قبل إتمام الطلب.',
    discountCodeHelp: 'اكتبي الكود إذا كان لديك كود خصم من ByJojo.',
    appliedCode: 'الكود المطبق',
    noPaymentMethodsCustomer: 'لا توجد طرق دفع متاحة حالياً. تواصلي مع ByJojo قبل تسجيل الطلب.',

    orderSuccessEyebrow: 'تم استلام الطلب',
    orderSuccessTitle: 'شكراً لك. طلب ByJojo أصبح قيد المتابعة.',
    orderSuccessCopy: 'تم حفظ طلبك وإرسال التفاصيل إلى فريق ByJojo. سيتم التواصل معك قريباً لتأكيد التوصيل والدفع.',
    orderSuccessMissing: 'تفاصيل الطلب غير متاحة',
    orderSuccessMissingCopy: 'لم نتمكن من تحميل صفحة التأكيد. يمكنك مراجعة طلباتك من الحساب.',
    continueShopping: 'متابعة التسوق',
    viewMyOrders: 'عرض طلباتي',
    instapayNextStep: 'الخطوة التالية لإنستاباي',
    instapaySuccessCopy: 'إذا اخترت إنستاباي، تأكدي من إرسال إثبات الدفع عبر الطريقة التي اخترتها أثناء إتمام الطلب.',
    orderItems: 'منتجات الطلب',
    piecesInOrder: '{count} قطعة في هذا الطلب',
    byjojoContactSoon: 'سيتواصل معك فريق ByJojo قريبًا لتأكيد الدفع وتفاصيل التوصيل.',

    account: 'الحساب',
    myOrdersTitle: 'طلباتي',
    myOrdersCopy: 'تابعي طلباتك من ByJojo والقطع الموجودة في كل طلب.',
    totalOrders: 'إجمالي الطلبات',
    noOrdersYet: 'لا توجد طلبات بعد',
    noOrdersCopy: 'ستظهر طلبات ByJojo هنا بعد إتمام الشراء.',
    couldNotLoadOrders: 'تعذر تحميل الطلبات',
    order: 'طلب',
    qty: 'الكمية',

    aboutEyebrow: 'عن ByJojo',
    aboutTitle: 'طريقة أنعم لتنسيق الطاولة.',
    aboutCopy: 'ByJojo براند منزلي فاخر لمفروشات الطاولة مبني على نقوش أنيقة وألوان طبيعية وقطع بسيطة تجعل الضيافة أجمل بدون تعقيد.',
    contactEyebrow: 'تواصل معنا',
    contactTitle: 'يسعدنا مساعدتك.',
    contactOrdersTitle: 'الطلبات',
    contactOrdersCopy: 'للاستفسار عن المقاسات أو التوصيل أو المنتجات، تواصلي معنا على واتساب أو إنستجرام.',
    collaborations: 'التعاون',
    collaborationsCopy: 'لتنسيق المنازل أو الهدايا أو التعاونات، أرسلي لنا عبر البريد الإلكتروني.',
    whatsapp: 'واتساب',
    instagram: 'إنستجرام',
    emailByJojo: 'راسل ByJojo',
    notFoundTitle: 'الصفحة غير موجودة',
    notFoundCopy: 'هذه الصفحة غير متاحة. لنعود إلى المجموعة.',
    goToShop: 'الذهاب للمتجر',

    loginTitle: 'تسجيل الدخول',
    password: 'كلمة المرور',
    loggingIn: 'جار تسجيل الدخول...',
    newToByJojo: 'جديدة على ByJojo؟',
    createAccount: 'إنشاء حساب',
    signupTitle: 'إنشاء حساب',
    creating: 'جار الإنشاء...',
    signup: 'تسجيل',
    alreadyAccount: 'لديك حساب بالفعل؟',
    adminLoginTitle: 'تسجيل دخول الإدارة',
    adminLoginCopy: 'استخدمي حساب الإدارة الذي تم إنشاؤه من ملف seed.',

    footerEyebrow: 'مفروشات طاولة فاخرة',
    footerCopy: 'مفروشات طاولة مطبوعة ودافئة للضيافة والهدايا والتفاصيل اليومية الجميلة.',
    visitCollection: 'زوري المجموعة',
    shopLatest: 'تسوقي أحدث القطع',
    explore: 'تصفح',
    footerRights: 'جميع الحقوق محفوظة.',
    footerLine: 'مصممة لبيوت دافئة وطاولات جميلة.',
    tableLinen: 'مفروشات طاولة',
    toggleMenu: 'فتح أو إغلاق القائمة',
    viewProduct: 'عرض المنتج',
    curatedWarmerTable: 'قطع مختارة لطاولة أكثر دفئًا.',
    premiumTableLinen: 'مفروشات طاولة فاخرة',
    quality: 'الجودة',
    contactOptions: 'طرق التواصل',
    byjojoSupport: 'دعم ByJojo',
    contactClosingTitle: 'أرسلي التفاصيل، وفريق ByJojo سيساعدك.',
    contactClosingCopy: 'لأسرع رد، ارسلي اسم المنتج، منطقتك، وطريقة الدفع المناسبة لك.',
    emailNotAdded: 'لم تتم إضافة البريد بعد',
    instapayQrAlt: 'رمز QR لإنستاباي',
    relatedProductsEyebrow: 'قد يعجبك أيضًا',
    relatedProductsTitle: 'قطع تكمل نفس الإحساس',
    productSeoFallback: 'قطعة مفروشات طاولة فاخرة من ByJojo لتنسيق طاولة أنيق.',
    printedLinen: 'لينن مطبوع',
    embroidery: 'تطريز',
    code: 'الكود',
    discountType: 'نوع الخصم',
    discountValue: 'قيمة الخصم',
    expiryDate: 'تاريخ الانتهاء',
    ownerNote: 'ملاحظة للإدارة',
    codePreview: 'معاينة الكود',
    offerPreview: 'معاينة العرض',
    useAtCheckout: 'يستخدم عند الدفع',
    minimum: 'الحد الأدنى',
    expires: 'ينتهي',
    status: 'الحالة',
    unlimited: 'بلا حد',
    noExpiry: 'بدون انتهاء',
    existingCodes: 'الأكواد الحالية',
    searchDiscountCodes: 'ابحثي في أكواد الخصم...',
    discountCodesFoundEmpty: 'لا توجد أكواد خصم',
    discountCodesFoundEmptyCopy: 'أنشئي كودًا للحملات أو العملاء المميزين أو عروض الدفع المؤقتة.',
    discountCodeCreated: 'تم إنشاء كود الخصم',
    discountCodeUpdated: 'تم تحديث كود الخصم',
    couldNotSaveDiscountCode: 'تعذر حفظ كود الخصم',
    couldNotDeleteDiscountCode: 'تعذر حذف كود الخصم',
    couldNotEmailDiscountCode: 'تعذر إرسال كود الخصم بالبريد',
    codeCopied: 'تم نسخ الكود',
    couldNotCopyCode: 'تعذر نسخ الكود',
    confirmDeleteDiscountCode: 'حذف كود الخصم "{code}"؟',
    confirmEmailDiscountCode: 'إرسال "{code}" لكل العملاء المسجلين؟',
    confirmDeleteProduct: 'حذف "{name}"؟',
    confirmDeleteCategory: 'حذف "{name}"؟',
    confirmDeleteOffer: 'حذف العرض "{title}"؟',
    confirmEmailOffer: 'إرسال "{title}" لكل العملاء المسجلين؟',
    confirmDeleteMessage: 'لا يمكن التراجع عن هذا الإجراء.',
    confirmEmailMessage: 'سيصل هذا البريد إلى العملاء المسجلين.',
    discountCodesNoteFull: 'أنشئي أكواد خصم أنيقة بحد أدنى للطلب، وتواريخ انتهاء، وحدود استخدام، وحملات بريدية للعملاء. يتم التحقق من الأكواد مرة أخرى في الخادم أثناء الدفع.',
    discountCodeFormHelp: 'حددي الكود، قيمة الخصم، شروط الاستخدام، وهل يمكن للعملاء استخدامه عند الدفع.',
    discountOwnerNoteCopy: 'أكواد النسبة مناسبة لحملات مثل "خصم 10%". الأكواد الثابتة مناسبة لقيم واضحة مثل "خصم 500 جنيه". الخادم يعيد حساب الخصم عند تسجيل الطلب حتى لا يمكن تعديل الإجمالي من المتصفح.',
    existingCodesCopy: 'أديري أكواد الحملات، انسخيها بسرعة، أو أرسليها بالبريد للعملاء المسجلين.',
    usageProgress: 'تقدم الاستخدام',
    usesRemaining: 'متبقي {count} استخدام',
    noUsageLimit: 'هذا الكود بدون حد استخدام.',
    noCategory: 'بدون قسم',
    customer: 'عميل',
    openOrders: 'فتح الطلبات',
    manageProducts: 'إدارة المنتجات',
    orderActivity: 'نشاط الطلبات',
    recentOrders: 'أحدث الطلبات',
    inventory: 'المخزون',
    lowStock: 'مخزون منخفض',
    performance: 'الأداء',
    bestSellingPieces: 'القطع الأكثر مبيعًا',
    noLowStockProducts: 'لا توجد منتجات منخفضة المخزون حاليًا.',
    bestSellingEmpty: 'ستظهر المنتجات الأكثر مبيعًا بعد تسجيل الطلبات.',
    left: 'متبقي',
    sold: 'تم بيع',
    averageOrder: 'متوسط الطلب',
    today: 'اليوم',
    pending: 'قيد الانتظار',
    awaitingPayment: 'بانتظار الدفع',
    awaitingPaymentNote: 'طلبات إنستاباي التي تحتاج تأكيد',
    registeredCustomerAccounts: 'حسابات عملاء مسجلة',
    activeHidden: '{active} نشط · {hidden} مخفي',
    lowStockNote: 'منتجات بها 3 قطع أو أقل',
    dashboardNoteFull: 'لمحة سريعة عن ByJojo: المبيعات، الطلبات، متابعة الدفع، القطع منخفضة المخزون، ونشاط العملاء الأخير.',
    lowStockCopy: 'حدّثي هذه المنتجات قبل نفادها.',
    customerCommunity: 'مجتمع العملاء',
    customersNoteFull: 'يظهر العملاء المسجلون هنا مع عدد الطلبات، إجمالي الإنفاق، تاريخ آخر طلب، وروابط تواصل سريعة.',
    searchCustomers: 'ابحثي بالاسم أو البريد أو الهاتف...',
    registeredCustomers: 'العملاء المسجلون',
    customerOrders: 'طلبات العملاء',
    customerRevenue: 'إيرادات العملاء',
    totalSpent: 'إجمالي الإنفاق',
    lastOrder: 'آخر طلب',
    noCustomersFound: 'لم يتم العثور على عملاء',
    noCustomersFoundCopy: 'جربي كلمة بحث أخرى أو انتظري إنشاء العملاء لحساباتهم.',
    orderStatusPending: 'قيد الانتظار',
    orderStatusConfirmed: 'تم التأكيد',
    orderStatusPreparing: 'قيد التحضير',
    orderStatusOutForDelivery: 'خرج للتوصيل',
    orderStatusDelivered: 'تم التوصيل',
    orderStatusCancelled: 'ملغي',
    paymentStatusPending: 'قيد الانتظار',
    paymentStatusAwaitingConfirmation: 'بانتظار التأكيد',
    paymentStatusPaid: 'مدفوع',
    couldNotUpdateOrder: 'تعذر تحديث الطلب',
    couldNotUpdatePaymentStatus: 'تعذر تحديث حالة الدفع',
    timing: 'التوقيت',

    adminOwnerTools: 'أدوات الإدارة',
    adminProductsTitle: 'المنتجات',
    adminProductsNote: 'أضيفي أو عدلي المنتجات هنا. يمكنك تحديث الأسعار والوصف والأقسام والصور في أي وقت. لأفضل نتيجة استخدمي صورًا واضحة مربعة أو رأسية بإضاءة طبيعية.',
    adminAddProduct: 'إضافة منتج جديد',
    adminEditProduct: 'تعديل المنتج',
    adminProductImageNote: 'اختاري صور المنتج من جهازك. سيتم رفعها تلقائيًا على Cloudinary.',
    productName: 'اسم المنتج',
    productNameAr: 'اسم المنتج بالعربية',
    priceEgp: 'السعر بالجنيه',
    selectCategory: 'اختاري القسم',
    description: 'الوصف',
    descriptionAr: 'الوصف بالعربية',
    featuredOnHome: 'مميز في الرئيسية',
    visibleInShop: 'ظاهر في المتجر',
    productImages: 'صور المنتج',
    mainImageNote: 'الصورة الرئيسية تظهر في كروت المنتجات.',
    chooseImage: 'اختيار صورة',
    replaceImage: 'استبدال الصورة',
    uploading: 'جار الرفع...',
    mainImage: 'الصورة الرئيسية',
    setMain: 'اجعلها الرئيسية',
    imagesReady: 'صور جاهزة',
    updateProduct: 'تحديث المنتج',
    addProduct: 'إضافة المنتج',
    searchProducts: 'ابحثي باسم المنتج أو القسم...',

    adminCategoriesTitle: 'الأقسام',
    adminCategoriesNote: 'أنشئي وأديري أقسام المنتجات. يمكنك إخفاء القسم بدون حذفه، وتحديد ظهوره في الصفحة الرئيسية.',
    storeStructure: 'هيكل المتجر',
    addCategory: 'إضافة قسم',
    updateCategory: 'تحديث القسم',
    addNewCategory: 'إضافة قسم جديد',
    editCategory: 'تعديل القسم',
    categoryName: 'اسم القسم',
    categoryImage: 'صورة القسم',
    showOnHome: 'يظهر في الرئيسية',
    activeInShop: 'نشط في المتجر',

    settingsTitle: 'الإعدادات',
    settingsEyebrow: 'إعدادات الدفع',
    settingsNote: 'رسوم التوصيل ورقم إنستاباي وصورة QR تظهر أثناء إتمام الطلب. أي تغيير هنا يظهر تلقائيًا في الموقع.',
    storeSettings: 'إعدادات المتجر',
    storeSettingsCopy: 'حافظي على بيانات التواصل والدفع والإعلان محدثة للعملاء.',
    storeName: 'اسم المتجر',
    deliveryFee: 'رسوم التوصيل',
    whatsappNumber: 'رقم واتساب',
    instagramUrl: 'رابط إنستجرام',
    contactEmail: 'البريد للتواصل',
    announcementText: 'نص الإعلان',
    instapayQr: 'QR إنستاباي',
    instapayQrCopy: 'العملاء يرون هذه الصورة عند اختيار إنستاباي أثناء الدفع.',
    saveSettings: 'حفظ الإعدادات',
    replaceQr: 'استبدال صورة QR',
    chooseQr: 'اختيار صورة QR',
    paymentMethods: 'طرق الدفع',
    checkoutAvailability: 'إتاحة الدفع',
    paymentSettingsCopy: 'فعّلي أو أوقفي طرق الدفع. العملاء سيرون الطرق المتاحة فقط أثناء إتمام الطلب.',
    cashToggleCopy: 'العملاء يمكنهم الدفع عند وصول الطلب.',
    instapayToggleCopy: 'العملاء يمكنهم التحويل عبر إنستاباي وإرسال الإثبات.',
    paymentMethodWarning: 'يجب تفعيل طريقة دفع واحدة على الأقل قبل الإطلاق.',
    instapayDisabledNote: 'إنستاباي غير مفعّل حالياً. سيتم حفظ الرقم و QR، لكن العملاء لن يروه أثناء الدفع.',

    overviewTitle: 'نظرة عامة / التحليلات',
    overviewNote: 'استخدمي هذه اللوحة لمراجعة نشاط المتجر والمبيعات وعدد المنتجات والعملاء والطلبات الحديثة بسرعة.',
    products: 'المنتجات',
    customers: 'العملاء',
    revenue: 'الإيرادات',
    adminOrdersTitle: 'الطلبات',
    adminOrdersNote: 'راجعي الطلبات الجديدة هنا، ثم حدّثي حالة الطلب أثناء انتقاله من التأكيد إلى التسليم.',
    orderUpdated: 'تم تحديث الطلب',
    orderStatus: 'حالة الطلب',
    paymentStatus: 'حالة الدفع',
    orderDetails: 'تفاصيل الطلب',
    noOrdersAdmin: 'لا توجد طلبات بعد',
    noOrdersAdminCopy: 'ستظهر طلبات العملاء الجديدة هنا.',
    reviewOrdersCopy: 'راجعي طلبات العملاء، أكدي مدفوعات إنستاباي، وحرّكي الطلب بين التحضير والتوصيل.',

    offersTitle: 'العروض',
    offersNote: 'يمكن تطبيق العروض على منتجات محددة فقط. سيظهر سعر العرض تلقائيًا للعميل في المتجر وصفحة المنتج.',
    offerTitle: 'عنوان العرض',
    percentage: 'نسبة مئوية',
    fixed: 'قيمة ثابتة',
    salePrice: 'سعر عرض',
    updateOffer: 'تحديث العرض',
    createOffer: 'إنشاء عرض',
    chooseProducts: 'اختيار المنتجات',
    selectedPieces: 'القطع المختارة',
    existingOffers: 'العروض الحالية',
    noOffersYet: 'لا توجد عروض بعد',

    discountCodesTitle: 'أكواد الخصم',
    discountCodesNote: 'أنشئي أكواد خصم للعملاء مع حد أدنى للطلب وحد استخدام. يمكنك إرسال الأكواد للعملاء المسجلين من هنا.',
    minimumOrder: 'الحد الأدنى للطلب',
    usageLimit: 'حد الاستخدام',
    updateCode: 'تحديث الكود',
    createCode: 'إنشاء كود',
    used: 'استخدم',
  },
};

function interpolate(template, values = {}) {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('byjojoLanguage') || 'en');
  const isArabic = language === 'ar';

  useEffect(() => {
    localStorage.setItem('byjojoLanguage', language);
    document.documentElement.lang = language;
    document.documentElement.dir = isArabic ? 'rtl' : 'ltr';
  }, [language, isArabic]);

  const toggleLanguage = () => setLanguage((current) => (current === 'en' ? 'ar' : 'en'));

  const t = (key, values) => {
    const template = translations[language]?.[key] || translations.en[key] || key;
    return values ? interpolate(template, values) : template;
  };

  const statusLabel = (status, type = 'general') => {
    const normalized = String(status || '')
      .split('-')
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');

    const scopedKey = type === 'payment'
      ? `paymentStatus${normalized}`
      : type === 'order'
        ? `orderStatus${normalized}`
        : status;

    const label = t(scopedKey);
    if (label !== scopedKey) return label;

    return String(status || '-')
      .split('-')
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(' ') || '-';
  };

  const value = useMemo(
    () => ({
      language,
      isArabic,
      toggleLanguage,
      t,
      statusLabel,
    }),
    [language, isArabic],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
